"""Add owner_id field to PlanShare

Revision ID: 02900b7e2e30
Revises: be0fe0db415d
Create Date: 2026-06-24 20:48:09.335556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02900b7e2e30'
down_revision: Union[str, Sequence[str], None] = 'be0fe0db415d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'exercises', ['owner_id', 'name'])
    op.add_column('plan_shares', sa.Column('owner_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_plan_shares_owner_id'), 'plan_shares', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'plan_shares', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plan_shares', type_='foreignkey')
    op.drop_index(op.f('ix_plan_shares_owner_id'), table_name='plan_shares')
    op.drop_column('plan_shares', 'owner_id')
    op.drop_constraint(None, 'exercises', type_='unique')
    # ### end Alembic commands ###
