"""Rename point

Revision ID: 32f7f2fde512
Revises: 6cfee36813df
Create Date: 2026-07-11 10:48:48.600369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32f7f2fde512'
down_revision: Union[str, Sequence[str], None] = '6cfee36813df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_logs', sa.Column('sync_datapoint_name', sa.String(length=512), nullable=True))
    op.create_unique_constraint(None, 'workout_logs', ['sync_datapoint_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workout_logs', type_='unique')
    op.drop_column('workout_logs', 'sync_datapoint_name')
    # ### end Alembic commands ###
