"""Modify unique constraint on exercise

Revision ID: 514989ce51d0
Revises: 02900b7e2e30
Create Date: 2026-06-25 13:21:02.855474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '514989ce51d0'
down_revision: Union[str, Sequence[str], None] = '02900b7e2e30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('exercises_owner_id_name_key'), 'exercises', type_='unique')
    op.create_index('uq_exercises_owner_name_active', 'exercises', ['owner_id', 'name'], unique=True, postgresql_where=sa.text('is_archived = false'))
    op.create_unique_constraint('uq_set_logs_log_exercise_index', 'set_logs', ['workout_log_id', 'exercise_id', 'set_index'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_set_logs_log_exercise_index', 'set_logs', type_='unique')
    op.drop_index('uq_exercises_owner_name_active', table_name='exercises', postgresql_where=sa.text('is_archived = false'))
    op.create_unique_constraint(op.f('exercises_owner_id_name_key'), 'exercises', ['owner_id', 'name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
