"""Synchronized column for WorkoutLog

Revision ID: 6cfee36813df
Revises: 0c8995460f45
Create Date: 2026-07-11 09:09:07.503252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cfee36813df'
down_revision: Union[str, Sequence[str], None] = '0c8995460f45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_logs', sa.Column('synchronized', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_workout_logs_synchronized'), 'workout_logs', ['synchronized'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_logs_synchronized'), table_name='workout_logs')
    op.drop_column('workout_logs', 'synchronized')
    # ### end Alembic commands ###
