"""Remove gt=0 from set log

Revision ID: a994fe8f8cb5
Revises: ccfa1f5dc4ac
Create Date: 2026-06-28 07:27:14.549267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a994fe8f8cb5'
down_revision: Union[str, Sequence[str], None] = 'ccfa1f5dc4ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
