"""add SetLog constraint

Revision ID: ccfa1f5dc4ac
Revises: 514989ce51d0
Create Date: 2026-06-25 19:44:08.053622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccfa1f5dc4ac'
down_revision: Union[str, Sequence[str], None] = '514989ce51d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('set_logs', 'rpe')
    workout_log_status = sa.Enum('IN_PROGRESS', 'COMPLETED', name='workoutlogstatus')
    workout_log_status.create(op.get_bind())
    op.add_column('workout_logs', sa.Column('status', workout_log_status, nullable=False))
    op.create_index(op.f('ix_workout_logs_status'), 'workout_logs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_logs_status'), table_name='workout_logs')
    op.drop_column('workout_logs', 'status')
    sa.Enum(name='workoutlogstatus').drop(op.get_bind())
    op.add_column('set_logs', sa.Column('rpe', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
