FROM node:24-alpine AS builder

WORKDIR /app
COPY package.json package-lock.json /app/
RUN npm ci

COPY . .
RUN npm run build


FROM nginx:1.31.2-alpine

COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]