apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: quickfit-api
    newName: ghcr.io/mszal449/quickfit-api
    newTag: latest
  - name: quickfit-frontend
    newName: ghcr.io/mszal449/quickfit-frontend
    newTag: latest
  - name: quickfit-worker
    newName: ghcr.io/mszal449/quickfit-worker
    newTag: latest

patches:
  - target:
      kind: Ingress
      name: quickfit
    patch: |-
      - op: add
        path: /metadata/annotations/cert-manager.io~1cluster-issuer
        value: letsencrypt-prod
      - op: add
        path: /spec/ingressClassName
        value: nginx
      - op: replace
        path: /spec/rules/0/host
        value: gohtonomi.com
      - op: add
        path: /spec/tls
        value:
          - hosts:
              - gohtonomi.com
            secretName: quickfit-tls

  - target:
      kind: Deployment
      name: frontend
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi

  - target:
      kind: Deployment
      name: backend
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
