apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: quickfit-api
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: backend-secret
          readinessProbe: # TODO: replace with /health
            httpGet:
              path: /api/health
              port: 8000
            initialDelaySeconds: 3
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8000
            initialDelaySeconds: 15